common/nng/socket.cpp: SubSocker::Receive(): return correct type
This function returns a Message pointer, so return NULL instead of
false.

Fixes:
../common/nng/socket.cpp: In member function ‘std::unique_ptr<mapf::Message> mapf::SubSocket::Receive(int)’:
../common/nng/socket.cpp:226:10: error: could not convert ‘false’ from ‘bool’ to ‘std::unique_ptr<mapf::Message>’
   return false;
          ^~~~~

Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>